import subprocess
from crewai import Agent, Task, Crew, LLM
from crewai.tools import tool
import analytics
import json
import os
from dotenv import load_dotenv
# from langchain_openai import AzureChatOpenAI


# Utility: run an external Python script and capture its output
def run_external(script_path):
    """Run an external Python script and return its output."""
    try:
        output = subprocess.check_output(
            ['python', script_path],
            text=True,
            stderr=subprocess.STDOUT
        )
        return {
                "returncode": subprocess.returncode,
                "stdout": subprocess.stdout,
                "stderr": subprocess.stderr,
                }
    except subprocess.CalledProcessError as e:
        return f"Program failed with output:\n{e.output}"
    except Exception as e:
        return str(e)

@tool
def list_enabled_reports():
    """List all enabled report modules."""
    enabled_reports = []
    for module in analytics.chart_modules:
        module_id = module[0]
        description = module[1]
        script_path = module[2]
        enabled = module[3]
        if enabled:
            enabled_reports.append(f"Module {module_id}: {description} ({script_path})")
    return "\n".join(enabled_reports)

@tool
def run_enabled_reports():
    """
    Run all enabled chart modules defined in analytics.py.
    """
    results = []
    results.append(
        f"Start Date and Time: "
        f"{analytics.get_current_et_timestamp()}"
    )

    for module in analytics.chart_modules:
        module_id = module[0]
        description = module[1]
        script_path = module[2]
        enabled = module[3]
        arguments = module[4]
        if not enabled:
            continue
        try:
            process = subprocess.run(
                ["python", script_path, json.dumps(arguments)],
                capture_output=True,
                text=True
            )
            results.append(
                f"\n{'='*80}\n"
                f"Module {module_id}: {description}\n"
                f"{'='*80}\n"
                f"{process.stdout}"
            )
            if process.stderr:
                results.append(
                    f"\nERRORS:\n{process.stderr}"
                )
        except Exception as e:
            results.append(
                f"\nFailed: {description}\n{str(e)}"
            )

    results.append(
        f"\nEnd Date and Time: "
        f"{analytics.get_current_et_timestamp()}"
    )
    return "\n".join(results)

@tool
def run_report(report_name):
    """
    Run a specific report module by name.
    """
    for module in analytics.chart_modules:
        if module[1] == report_name:
            script_path = module[2]
            arguments = module[4]
            try:
                process = subprocess.run(
                    ["python", script_path, json.dumps(arguments)],
                    capture_output=True,
                    text=True
                )
                return (
                    f"Module: {report_name}\n"
                    f"{'='*80}\n"
                    f"{process.stdout}\n"
                    f"{'='*80}\n"
                    f"Errors:\n{process.stderr}" if process.stderr else ""
                )
            except Exception as e:
                return f"Failed to run {report_name}: {str(e)}"
    return f"Report '{report_name}' not found."

load_dotenv()

azure_openai_api_key = os.getenv("AZURE_OPENAI_API_KEY")
azure_openai_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
azure_openai_model_deployment = os.getenv("AZURE_OPENAI_MODEL_DEPLOYMENT")
azure_openai_api_version = os.getenv("AZURE_OPENAI_API_VERSION")

print("azure_openai_api_key:", azure_openai_api_key)
print("azure_openai_endpoint:", azure_openai_endpoint)
print("azure_openai_model_deployment:", azure_openai_model_deployment)
print("azure_openai_api_version:", azure_openai_api_version)

llm = LLM(
    model=f"azure/{azure_openai_model_deployment}",
    api_key=azure_openai_api_key,
    base_url=azure_openai_endpoint,
    api_version=azure_openai_api_version
)

print("LLM:",type(llm))

# Define the agent
analytics_agent = Agent(
    role="Data Analytics Agent",
    goal="Execute selected report modules and summarize their outputs.",
    backstory=(
        "Run data analytics scripts, collect their outputs, "
        "and provide clear summaries."
    ),
    tools=[run_enabled_reports],
    llm=llm
)

# Define the task
task_expected_output = """
A report containing:
- Execution status of each module
- Output generated by each module
- Any errors encountered
"""
# - A summary of the results

task = Task(
#    description="Run all selected report modules and return each report.",
    description=
"""    
    Only run the report module 'Flexibility vs Soreness — Single‑Day Snapshot' and return the report.
    Do not run any other enabled reports.
""",
    agent=analytics_agent,
    expected_output=task_expected_output
)

# Crew orchestration
crew = Crew(
    agents=[analytics_agent],
    tasks=[task]
)

if __name__ == "__main__":
    result = crew.kickoff()
    print(result)