scatter_markers = \
"""
🔹 Basic markers
"." → point
"," → pixel
"o" → circle
"v" → triangle down
"^" → triangle up
"<" → triangle left
">" → triangle right
"1" → tri-down (small)
"2" → tri-up (small)
"3" → tri-left (small)
"4" → tri-right (small)

🔹 Squares, diamonds, and stars
"s" → square
"p" → pentagon
"P" → plus (filled)
"*"→ star
"h" → hexagon1
"H" → hexagon2
"D" → diamond
"d" → thin diamond

🔹 Lines and crosses
"|" → vertical line
"_" → horizontal line
"+" → plus
"x" → cross (x-shape)
"X" → filled X
"""
joints = ["Shoulder", "Elbow", "Wrist", "Hip", "Knee", "Ankle"]
joints_to_chart = [("Shoulder",True),("Elbow",True),("Wrist",True),("Hip",True),("Knee",True),("Ankle",True)]
workout_types = ["CAR/Mobility","Tendon Training","Elliptical Cardio","Treadmill Cardio","Weight Training"]
health_analysis_charts = "charts/health-analysis/"
protein_consumption_charts = "charts/protein-consumption/"
weight_training_charts = "charts/weight-training/"
file_extensions = [".pdf", ".svg"]
spreadsheet = "fitness-log.ods"


def show_scatter_marker():
    return scatter_markers

def format_joints_list(items):
    l = []
    for item in items:
        if not isinstance(item[0], str):
        # Raise a TypeError with a clear message
            raise TypeError(f"For list element {item}, the first value '{item[0]}' in the tuple must be a string, "
                            f"but got type '{type(item[0])}'.")
        else:
            l.append((item[0].lower().capitalize(),item[1]))
    return l

# List generated by generate_exercise_data.py 
exercise_list = [
"Pull Ups",
"Rear Delt Flies",       
"Face Pulls",
"Side Delt Cable Raises",
"Side Delt Raises",      
"Tricep Extensions",
"Tricep Pulldowns",
"Back Extensions",
"Leg Press",
"Leg Extensions",
"Hamstring Curls",
"Calf Raises",
"Hip Thrusts",
"Pectoral Flies",
"Rows",
"Preacher Curls",
"Upright Cable Rows",
"Abdominal Cable Crunches",
"Hip Abduction",
"Hip Adduction",
"Chin Ups",
"Shoulder CARs",
"Hip CARs",
"Knee CARs",
"Ankle CARs",
"Wrist CARs",
"90/90 Hip Rotation Stretch",
"Hip Elliptical",
"Reverse Walking",
"Side Walking (Left and Right)",
"Deep Squat Hold",
"Goblet Squat Hold"    
]

# List generated by generate_exercise_data.py 
exercise_elements_list = [
('Pull Ups', 2, '', 'CAR/Mobility', 'Y') ,
('Rear Delt Flies', 2, '', 'Weight Training', 'N') ,
('Face Pulls', 2, '', 'Weight Training', 'Y') ,
('Side Delt Cable Raises', 2, '', 'Weight Training', 'N') ,
('Side Delt Raises', 2, '', 'Weight Training', 'Y') ,
('Tricep Extensions', 2, '', 'Weight Training', 'N') ,
('Tricep Pulldowns', 2, '', 'Weight Training', 'Y') ,
('Back Extensions', 2, '', 'Weight Training', 'Y') ,
('Leg Press', 2, '', 'Weight Training', 'Y') ,
('Leg Extensions', 2, '', 'Weight Training', 'Y') ,
('Hamstring Curls', 2, '', 'Weight Training', 'Y') ,
('Calf Raises', 2, '', 'Weight Training', 'Y') ,
('Hip Thrusts', 2, '', 'Weight Training', 'Y') ,
('Pectoral Flies', 2, '', 'Weight Training', 'Y') ,
('Rows', 2, '', 'Weight Training', 'Y') ,
('Preacher Curls', 2, '', 'Weight Training', 'Y') ,
('Upright Cable Rows', 2, '', 'Weight Training', 'Y') ,
('Abdominal Cable Crunches', 2, '', 'Weight Training', 'Y') ,
('Hip Abduction', 2, '', 'Weight Training', 'Y') ,
('Hip Adduction', 2, '', 'Weight Training', 'Y') ,
('Chin Ups', 2, '', 'CAR/Mobility', 'Y') ,
('Shoulder CARs', 1, 5, 'CAR/Mobility', 'Y') ,
('Hip CARs', 1, 5, 'CAR/Mobility', 'Y') ,
('Knee CARs', 1, 10, 'CAR/Mobility', 'Y') ,
('Ankle CARs', 1, 30, 'CAR/Mobility', 'Y') ,
('Wrist CARs', 1, 30, 'CAR/Mobility', 'Y') ,
('90/90 Hip Rotation Stretch', 2, '90 seconds per hip', 'CAR/Mobility', 'Y') ,
('Hip Elliptical', 1, '15 minutes', 'Elliptical Cardio', 'Y') ,
('Reverse Walking', 1, '15 minutes', 'Treadmill Cardio', 'Y') ,
('Side Walking (Left and Right)', 1, '5 minutes', 'Treadmill Cardio', 'Y') ,
('Deep Squat Hold', 2, '2 minutes', 'Tendon Training', 'Y') ,
('Goblet Squat Hold', 2, '1 minute', 'Tendon Training', 'Y')     
]